apiVersion: v1
kind: Pod  # Type of k8s object to deploy
metadata:
  name: amf-pod  # Name of the pod
  labels:
    app: amf  # Label assigned to Pod and used for selection
    version: v1
spec:
  containers:
  - name: amf-ctr  # Container name
    image: amf-ctr:1.0  # Container image
    ports:
    - containerPort: 8080  # Container port
 #   resources:   # Resource limits
 #     limits:
 #       cpu: 1
 #       memory: 256Mi
 #     requests:
 #       cpu: .5
 #       memory: 100Mi